### PR TITLE
Fix calls to parseFolder to stop processing folders multiple times; call...

### PR DESCRIPTION
**Pull request by rickselby**
...ing _check_folder more often to ensure the functions are not looking too deep (process one level at a time).

I'm not certain why folders are processed really, the Placemarks could just be iterated through; I suppose there are names associated with the folders that could be used somewhere. Didn't want to completely rewrite, just tweak so it wasn't drawing routes multiple times.

### CODE REVIEW

**Comment by rickselby** [comment]
Added fix to read long lists of co-ordinates in

**Comment by rickselby** [comment]
Added a way of getting the latLngs out from the kml file to pass to map.fitBounds(). I'm no javascript coder so I'm sure there's a nicer way of doing it than this...?

**Comment by shramov** [comment]
I've repackaged plugins into separate repository https://github.com/shramov/leaflet-plugins
Sorry but history of your first two fixes is lost :)

**Comment by severinmenard** [comment]
Hi,

Trying to contact you after a discussion with Martijn van Exel at SOTM about your fork of his Bing Analyzer. I volunteer for the humanitarian aspects of OSM and would be very interested to be able to get the resulting vector file to have a clear overview of what can be easily trace over imagery or not in the country hit by a humanitarian crisis. I would be happy if you can contact me on my email address severin.menard at gmail or on IRC (#hot on OFTC)

**Pull request closed without merging**
